/*
 * $Id$
 *
 * Here we store references to data strings containing the names of every class
 * belonging to this C++ Library
 */

namespace xvr2 {
#if __GNUC__ < 3
	const char *_xvr2Array = "Array";
	const char *_xvr2ArrayIndexOutOfLimitsException = "ArrayIndexOutOfLimitsException";
	const char *_xvr2BrokenPipeException = "BrokenPipeException";
	const char *_xvr2CantLoadDSOException = "CantLoadDSOException";
	const char *_xvr2CantUnloadDSOException = "CantUnloadDSOException";
	const char *_xvr2ConnectionRefusedException = "ConnectionRefusedException";
	const char *_xvr2ConnectionTimeoutException = "ConnectionTimeoutException";
	const char *_xvr2Container = "Container";
	const char *_xvr2DSOException = "DSOException";
	const char *_xvr2DSOSymbolException = "DSOSymbolException";
	const char *_xvr2ElementNotFoundException = "ElementNotFoundException";
	const char *_xvr2Exception = "Exception";
	const char *_xvr2System = "System";
	const char *_xvr2Threading = "Threading";
	const char *_xvr2IOException = "IOException";
	const char *_xvr2List = "List";
	const char *_xvr2Mutex = "Mutex";
	const char *_xvr2MutexException = "MutexException";
	const char *_xvr2NetworkException = "NetworkException";
	const char *_xvr2NetworkUnreachableException = "NetworkUnreachableException";
	const char *_xvr2nodeT = "nodeT";
	const char *_xvr2NoMoreTokensException = "NoMoreTokensException";
	const char *_xvr2NullPointerException = "NullPointerException";
	const char *_xvr2NumberException = "NumberException";
	const char *_xvr2Object = "Object";
	const char *_xvr2Plugin = "Plugin";
	const char *_xvr2ProcOutOfFileDescriptorsException = "ProcOutOfFileDescriptorsException";
	const char *_xvr2TCPServerSocket = "TCPServerSocket";
	const char *_xvr2SharedVar = "SharedVar";
	const char *_xvr2Socket = "Socket";
	const char *_xvr2SocketAlreadyBoundedException = "SocketAlreadyBoundedException";
	const char *_xvr2SocketAlreadyUsedException = "SocketAlreadyUsedException";
	const char *_xvr2SocketUnableToReadException = "SocketUnableToReadException";
	const char *_xvr2SocketUnableToWriteException = "SocketUnableToWriteException";
	const char *_xvr2String = "String";
	const char *_xvr2SysOutOfFileDescriptorsException = "SysOutOfFileDescriptorsException";
	const char *_xvr2Thread = "Thread";
	const char *_xvr2Tokenizer = "Tokenizer";
	const char *_xvr2UnableToLockMutexException = "UnableToLockMutexException";
	const char *_xvr2UnableToUnlockMutexException = "UnableToUnlockMutexException";
	const char *_xvr2DeadLockException = "DeadLockException";
	const char *_xvr2ThreadException = "ThreadException";
	const char *_xvr2ThreadNotRunningException = "ThreadNotRunningException";
	const char *_xvr2FileExistsException = "FileExistsException";
	const char *_xvr2ThisIsADirectoryException = "ThisIsADirectoryException";
	const char *_xvr2PermissionDeniedException = "PermissionDeniedException";
	const char *_xvr2FilenameTooLongException = "FilenameTooLongException";
	const char *_xvr2FileOrDirectoryNotFoundException = "FileOrDirectoryNotFoundException";
	const char *_xvr2ThisIsNotADirectoryException = "ThisIsNotADirectoryException";
	const char *_xvr2DeviceOrFIFONotFoundException = "DeviceOrFIFONotFoundException";
	const char *_xvr2DeviceNotFoundException = "DeviceNotFoundException";
	const char *_xvr2UnableToWriteOnReadOnlyFileException = "UnableToWriteOnReadOnlyFileException";
	const char *_xvr2UnableToWriteOnRunningExecutableFileException = "UnableToWriteOnRunningExecutableFileException";
	const char *_xvr2FilenameExceedsAddressSpaceException = "FilenameExceedsAddressSpaceException";
	const char *_xvr2TooManySymlinksException = "TooManySymlinksException";
	const char *_xvr2NotEnoughStorageSpaceException = "NotEnoughStorageSpaceException";
	const char *_xvr2NotEnoughKernelMemoryException = "NotEnoughKernelMemoryException";
	const char *_xvr2MaximumNumberOfOpenFilesForThisProcessException = "MaximumNumberOfOpenFilesForThisProcessException";
	const char *_xvr2MaximumNumberOfOpenFilesForThisSystemException = "MaximumNumberOfOpenFilesForThisSystemException";
	const char *_xvr2FileException = "FileException";
	const char *_xvr2FileNotOpenedException = "FileNotOpenedException";

	const char *_xvr2FeatureNotAvailableOnPipesOrSocketException = "FeatureNotAvailableOnPipesOrSocketException";
	const char *_xvr2InvalidParameterException = "InvalidParameterException";
        const char *_xvr2UserIDDoesNotMatchException = "UserIDDoesNotMatchException";
        const char *_xvr2SecurityException = "SecurityException";
        const char *_xvr2FileTooBigException = "FileTooBigException";
#ifdef USE_DEBUG
	const char *_xvr2__xvr2_DebugOutput = "__xvr2_DebugOutput";
#endif


	const char *_xvr2WriteWillBlockException = "WriteWillBlockException";
	const char *_xvr2InterruptedSystemCallException = "InterruptedSystemCallException";
	const char *_xvr2Date = "Date";
	const char *_xvr2BaseFile = "BaseFile";
	const char *_xvr2Unix = "Unix";
	const char *_xvr2Time = "Time";
	const char *_xvr2Timestamp = "Timestamp";
	const char *_xvr2Chronometer = "Chronometer";
	const char *_xvr2TextOutput = "TextOutput";
	const char *_xvr2StandardError = "StandardError";
	const char *_xvr2StandardOutput = "StandardOutput";
	const char *_xvr2TextInput = "TextInput";
	const char *_xvr2StandardInput = "StandardInput";
	const char *_xvr2Memory = "Memory";
	const char *_xvr2MemoryException = "MemoryException";
	const char *_xvr2AllocationFailedException = "AllocationFailedException";
	const char *_xvr2ReallocFailedException = "ReallocFailedException";
	const char *_xvr2MathException = "MathException";
	const char *_xvr2TemporalBuffer = "TemporalBuffer";
	const char *_xvr2GarbageCollector = "GarbageCollector";
	const char *_xvr2List__nodeT = "List::nodeT";
	const char *_xvr2AutomatedGC = "AutomatedGC";
	const char *_xvr2Group = "Group";
	const char *_xvr2BufferTooSmallException = "BufferTooSmallException";
	const char *_xvr2GroupException = "GroupException";
	const char *_xvr2UserException = "UserException";
	const char *_xvr2User = "User";
	const char *_xvr2UserNotFoundException = "UserNotFoundException";
	const char *_xvr2GroupNotFoundException = "GroupNotFoundException";
	const char *_xvr2Syslog = "Syslog";
	const char *_xvr2ConditionVar = "ConditionVar";
	const char *_xvr2ConditionVarWaitTimedOutException = "ConditionVarWaitTimedOutException";
	const char *_xvr2Semaphore = "Semaphore";
	const char *_xvr2SemaphoreException = "SemaphoreException";
	const char *_xvr2SemaphoreInitValueException = "SemaphoreInitValueException";
	const char *_xvr2SemaphoreUnableToDestroyException = "SemaphoreUnableToDestroyException";
	const char *_xvr2SemaphoreUnableToDecreaseException = "SemaphoreUnableToDecreaseException";
	const char *_xvr2SemaphoreUnableToIncreaseException = "SemaphoreUnableToIncreaseException";
	const char *_xvr2Log = "Log";
	const char *_xvr2DBDriverInfo = "DBDriverInfo";
	const char *_xvr2FileNotFoundException = "FileNotFoundException";
	const char *_xvr2SQLDriver = "SQLDriver";
	const char *_xvr2SQLConnection = "SQLConnection";
	const char *_xvr2DatabaseException = "DatabaseException";
	const char *_xvr2DBServerUnreachableException = "DBServerUnreachableException";
	const char *_xvr2AlreadyConnected2DBException = "AlreadyConnected2DBException";
	const char *_xvr2DBConnectFirstException = "DBConnectFirstException";
	const char *_xvr2ResultSet = "ResultSet";
	const char *_xvr2SQLResultRow = "SQLResultRow";
	const char *_xvr2SQLField = "SQLField";
	const char *_xvr2Byte = "Byte";
	const char *_xvr2UndefinedClassException = "UndefinedClassException";
	const char *_xvr2StringException = "StringException";
	const char *_xvr2ParseException = "ParseException";
	const char *_xvr2DateParseException = "DateParseException";
	const char *_xvr2TimeParseException = "TimeParseException";
	const char *_xvr2BitParseException = "BitParseException";
	const char *_xvr2ByteParseException = "ByteParseException";
	const char *_xvr2NoDataFetchException = "NoDataFetchException";
	const char *_xvr2NoMoreRowsException = "NoMoreRowsException";
	const char *_xvr2DBConnectionFailedException = "DBConnectionFailedException";
	const char *_xvr2ServerDisconnectedException = "ServerDisconnectedException";
	const char *_xvr2SQLQueryException = "SQLQueryException";
	const char *_xvr2SQLQueryRDBMSDisconnectedException = "SQLQueryRDBMSDisconnectedException";
	const char *_xvr2UnableToParseQueryException = "UnableToParseQueryException";
	const char *_xvr2TCPSocket = "TCPSocket";
	const char *_xvr2ConfigFile = "ConfigFile";
	const char *_xvr2__ParamAndVal = "__ParamAndVal";
	const char *_xvr2Console = "Console";
	const char *_xvr2TCPServer = "TCPServer";
	const char *_xvr2TCPServerSession = "TCPServerSession";
	const char *_xvr2IPAddress = "IPAddress";
	const char *_xvr2HostNotFoundException = "HostNotFoundException";
	const char *_xvr2NSTryAgainException = "NSTryAgainException";
	const char *_xvr2NSFatalException = "NSFatalException";
	const char *_xvr2NoIPForYouException = "NoIPForYouException";
	const char *_xvr2ConnectionResetByPeerException = "ConnectionResetByPeerException";
	const char *_xvr2Connection = "DB::Conection";
	const char *_xvr2DBDriver = "DB::Driver";
	const char *_xvr2Field = "DB::Field";
#endif
};
